import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(req: Request) {
  try {
    const data = await req.json();
    const configPath = path.join(process.cwd(), 'src/config/products.ts');
    
    const code = `// Central config — edit these values to update the whole site.
// (Auto-generated by Admin Config page)

export const SITE_CONFIG = ${JSON.stringify(data, null, 2)} as const;
`;
    
    fs.writeFileSync(configPath, code, 'utf8');
    return NextResponse.json({ success: true });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
