import { Variant, Pack } from './types';

export const PACK_SIZES: Pack[] = [
  { count: 1,  price: 6,  label: "Single",      tag: null },
  { count: 5,  price: 24, label: "One chair",   tag: null },
  { count: 6,  price: 28, label: "+1 spare",    tag: "Best for 1" },
  { count: 10, price: 44, label: "Two chairs",  tag: null },
  { count: 12, price: 48, label: "Bulk",        tag: "Save 33%" },
];

export const PRODUCT_VARIANTS: Variant[] = [
  {
    key: "blueberry", name: "Blueberry", hex: "#4361EE",
    bg: "#E4E9FF", text: "#0E1640",  ring: "#2A45C7",
    accent: "#FFB4A2",
    headline: { line1: "Deep, calm,", lasso: "Blueberry", line2: "blue." },
    price: 24,
    blurb: "The classic Orbit — a saturated indigo that anchors any setup and pops against gray, oak, or rug.",
    features: [
      { icon: "Droplets",     title: "Indigo-saturation finish", sub: "Reads navy under lamplight." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Droplets",   text: "Gray-floor pairing" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "VolumeX",   text: "Whisper-quiet" },
    ],
    dark: false,
  },
  {
    key: "clover", name: "Clover",   hex: "#06D6A0",
    bg: "#E5F7EE", text: "#0A2A22",  ring: "#06D6A0",
    accent: "#5A74FF",
    headline: { line1: "Fresh take.", lasso: "Clover", line2: "guard." },
    price: 24,
    blurb: "A mint green that disappears into houseplants and Persian rugs alike. New for spring.",
    features: [
      { icon: "Leaf",         title: "Plant-safe colorway",   sub: "Reads like a hosta leaf." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Leaf",       text: "Plant-room friendly" },
      { icon: "VolumeX",   text: "Whisper-quiet" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
    ],
    dark: false,
  },
  {
    key: "coral",  name: "Coral",    hex: "#FFB4A2",
    bg: "#FFEEE8", text: "#3A1A12",  ring: "#FF6B47",
    accent: "#5A74FF",
    headline: { line1: "Warm room?", lasso: "Coral", line2: "is yours." },
    price: 24,
    blurb: "A muted peach that loves natural wood floors and golden-hour light.",
    features: [
      { icon: "Sun",          title: "Warm-tone match",        sub: "Pairs with oak & walnut." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Sun",        text: "Wood-floor friendly" },
      { icon: "Heart",      text: "Most-gifted" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
    ],
    dark: false,
  },
  {
    key: "lavender", name: "Lavender", hex: "#A292FF",
    bg: "#F1EEFF", text: "#1F1840",   ring: "#7C5CFF",
    accent: "#FFB4A2",
    headline: { line1: "Calm, but", lasso: "Lavender", line2: "punchy." },
    price: 24,
    blurb: "Soft purple that quietly dresses up any chair. Especially nice in studios and reading nooks.",
    features: [
      { icon: "Moon",         title: "Studio-friendly tone",   sub: "Soft on the eyes." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Moon",       text: "Reading-nook ready" },
      { icon: "VolumeX",   text: "Whisper-quiet" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
    ],
    dark: false,
  },
  {
    key: "fawn",   name: "Fawn",     hex: "#E7BC91",
    bg: "#FBF1E3", text: "#3A2614",  ring: "#9C6644",
    accent: "#06D6A0",
    headline: { line1: "Warm wood?", lasso: "Fawn", line2: "feels right." },
    price: 24,
    blurb: "A sandy tan tuned to oak and bamboo floors. Works on rugs too — disappears like it should.",
    features: [
      { icon: "TreePine",    title: "Hardwood match",         sub: "Oak, bamboo, ash." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "TreePine",  text: "Hardwood blend" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "Feather",    text: "Featherweight" },
    ],
    dark: false,
  },
  {
    key: "rooster", name: "Rooster", hex: "#FF3131",
    bg: "#FFE7E2", text: "#3A0808",  ring: "#B5161B",
    accent: "#06D6A0",
    headline: { line1: "Loud.", lasso: "Rooster", line2: "and proud." },
    price: 24,
    blurb: "For the people who put red on everything. Pops against neutral floors and rugs.",
    features: [
      { icon: "Flame",        title: "Boldest in the lineup",  sub: "Statement caster guards." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Flame",      text: "Statement piece" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "Zap",        text: "Limited drop" },
    ],
    dark: false,
  },
  {
    key: "flamingo", name: "Flamingo", hex: "#FF90FE",
    bg: "#FFE6FE", text: "#3B0D3A",  ring: "#C44FC1",
    accent: "#06D6A0",
    headline: { line1: "Pink, with", lasso: "Flamingo", line2: "energy." },
    price: 24,
    blurb: "An unapologetic pink for the people decorating in maximalist mode. Kids' rooms approve.",
    features: [
      { icon: "Sparkles",     title: "Maximalist pink",        sub: "Built to be seen." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Sparkles",   text: "Kids-room favorite" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "Heart",      text: "Most-gifted" },
    ],
    dark: false,
  },
  {
    key: "bear", name: "Bear", hex: "#9C6644",
    bg: "#F1E4D6", text: "#2A1608",  ring: "#7A4A2F",
    accent: "#06D6A0",
    headline: { line1: "Cozy as a", lasso: "Bear", line2: "in autumn." },
    price: 24,
    blurb: "A grounded chestnut brown for walnut desks, leather chairs, and the bookshelf life.",
    features: [
      { icon: "TreePine",    title: "Walnut-tone match",      sub: "Pairs with dark woods." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "BookOpen",       text: "Library-ready" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "Feather",    text: "Featherweight" },
    ],
    dark: false,
  },
  {
    key: "pomegranate", name: "Pomegranate", hex: "#950000",
    bg: "#F0D9D9", text: "#2A0808",  ring: "#700000",
    accent: "#E7BC91",
    headline: { line1: "Rich and", lasso: "Pomegranate", line2: "luxe." },
    price: 24,
    blurb: "A deep oxblood for the people whose rugs already have it. Quietly luxurious.",
    features: [
      { icon: "Wine",         title: "Deep oxblood",           sub: "For grown-up offices." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Wine",       text: "Studio-luxe palette" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "VolumeX",   text: "Whisper-quiet" },
    ],
    dark: false,
  },
  {
    key: "onyx",   name: "Onyx",     hex: "#212529",
    bg: "#15171B", text: "#FFFFFF",  ring: "#5A74FF",
    accent: "#FFB4A2",
    headline: { line1: "Goes with", lasso: "anything.", line2: "Even gaming chairs." },
    price: 24,
    blurb: "The stealth option. Matte black caster guards for the people who only own black furniture.",
    features: [
      { icon: "EyeOff",      title: "Disappears into dark",   sub: "Stealth on black bases." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "EyeOff",    text: "Stealth finish" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "Zap",        text: "Gamer-approved" },
    ],
    dark: true,
  },
  {
    key: "polar",  name: "Polar",    hex: "#F4F4F0",
    bg: "#FFFFFF", text: "#1A1B1F",  ring: "#5A74FF",
    accent: "#06D6A0",
    headline: { line1: "Pure,", lasso: "Polar", line2: "minimal." },
    price: 24,
    blurb: "Off-white that disappears against bright floors and modern studios. Quietly perfect.",
    features: [
      { icon: "Snowflake",    title: "Whisper-bright finish",  sub: "Reads as a soft glow under light." },
      { icon: "Armchair",     title: "Fits 95% of chairs",    sub: "Stems from 7 to 11mm." },
      { icon: "PawPrint",    title: "Paw & cord safe",       sub: "Tested by three curious cats." },
      { icon: "RotateCcw",   title: "60-day returns",        sub: "Free, no questions asked." },
    ],
    floatChips: [
      { icon: "Snowflake",  text: "Studio-bright" },
      { icon: "ShieldCheck", text: "Soft TPU shell" },
      { icon: "VolumeX",   text: "Whisper-quiet" },
    ],
    dark: false,
  },
];
